### ISSUE TITLE
submit app to codepath

### ISSUE THREAD

**Issue by ananavati** [ananavati/iosTipCalculator#1]
@timothy1ee @nesquena
tipCalculator app for the ios bootcamp, I signed up for the class with my email as nanavatiarpan@gmail.com

**Comment by timothy1ee** [comment]
Cool, great that you're playing around with improving the UI. I don't see the SettingsViewController though, have you pushed all your code?

**Comment by ananavati** [comment]
Oops sorry! Pushed the code with SettingsViewController

**Comment by timothy1ee** [comment]
Great, thanks for the submission! Hopefully, this gave you a sense for the basic iOS development process.

The next step is to schedule a 15 minute phone interview here: https://www.google.com/calendar/selfsched?sstoken=UVBDTi1jVkx4SldqfGRlZmF1bHR8MGVhNTlkZDFmYzQzODdkNDFhZjQ0NWQyZjFiMDU3Nzg. Let me know if none of those slots work.

When you choose a slot, can you edit the event with your phone number? Look forward to chatting!

**Comment by ananavati** [comment]
awesome! thanks for looking over the app. I updated the event with my phone
number in the description, look forward to chatting with you on Wednesday

On Sun, Feb 23, 2014 at 11:47 AM, Timothy Lee notifications@github.comwrote:

> Great, thanks for the submission! Hopefully, this gave you a sense for the
> basic iOS development process.
> 
> The next step is to schedule a 15 minute phone interview here:
> https://www.google.com/calendar/selfsched?sstoken=UVBDTi1jVkx4SldqfGRlZmF1bHR8MGVhNTlkZDFmYzQzODdkNDFhZjQ0NWQyZjFiMDU3Nzg.
> Let me know if none of those slots work.
> 
> When you choose a slot, can you edit the event with your phone number?
> Look forward to chatting!
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/ananavati/iosTipCalculator/issues/1#issuecomment-35840978
> .

## 

cheers Arpan!!

**Comment by ananavati** [comment]
hey Tim, 
Are we still doing the phone interview today?
